batch_size: 128
epochs: 40
model_name: rnn
output_dir: models/rnn
random_state: 420
train_set_size: 0.7
val_set_size: 0.15
data_dir: data
model_structure:
  n_layers: 2
  d_model: 128
  max_pos_encoding: 1024
  init_learning_rate: 0.0001
  dropout_rate: 0.3
  activations: [selu, sigmoid]
  dense_layer_class_ratio: 8
training:
  monitor: val_loss
  monitor_mode: min
  save_best_weights: True
  lr_reducing:
    monitor: val_loss
    patience: 3
    min_lr: 1.e-7
    mode: min
  early_stopping:
    patience: 5
    monitor: val_loss
    mode: min
    start_from_epoch: 1
